### ISSUE TITLE
Error on MacOS when trying to build

### ISSUE THREAD

**Issue by voyage11** [elastos/Elastos.ELA.SPV.Cpp.ID#59]
Instructions on Mac OS need to be clearer. I got error on when trying to build on Mac OS. I don't know what is the next step to take. 

Let's say I have successfully built the binary. We need the instructions on how to use the binary.

![erroronmacos](https://user-images.githubusercontent.com/1943839/45790715-cc285600-bcb8-11e8-8e85-fb9f8b9f4f9e.png)

```

fatal: bad revision 'HEAD'

CMake Error at ThirdParty/CMakeLists.txt:5 (add_subdirectory):
  The source directory

    /Developer/Elastos/Elastos.ELA.SPV.Cpp.ID-dev/ThirdParty/Elastos.ELA.SPV.Cpp

  does not contain a CMakeLists.txt file.


CMake Error at ThirdParty/CMakeLists.txt:9 (add_subdirectory):
  The source directory

    /Developer/Elastos/Elastos.ELA.SPV.Cpp.ID-dev/ThirdParty/leveldb

  does not contain a CMakeLists.txt file.


Configuring incomplete, errors occurred!
See also "/Developer/Elastos/Elastos.ELA.SPV.Cpp.ID-dev/cmake-build-ndk-release/CMakeFiles/CMakeOutput.log".
```

**Comment by voyage11** [comment]
@xiywang You are right. Previously I had `git@github.com: Permission denied (publickey).` error when I tried to run `git submodule update --init --recursive`. I just fixed it on my Mac. 

Now that I have completed until the last step `make`. I saw some errors like:-

`[2018-09-23 21:38:13.473] [console] [error] ElastosID IdCache::Put 1  begin _db->Put idid1 idJson{"path1":{"101":{"datahash":"datahash1","proof":"hello proof1","sign":"hello sign1"},"102":{"datahash":"datahash2","proof":"hello proof2","sign":"hello sign2"},"103":{"datahash":"datahash3","proof":"hello proof3","sign":"hello sign3"}},"path2":{"104":{"DataHash":"DataHash1","Proof":"hello proof1","Sign":"hello sign1"},"105":{"DataHash":"DataHash2","Proof":"hello proof2","Sign":"hello sign2"},"106":{"DataHash":"DataHash3","Proof":"hello proof3","Sign":"hello sign3"}},"path3":{"107":{"DataHash":"DataHash1","Proof":"hello proof1","Sign":"hello sign1"},"108":{"DataHash":"DataHash2","Proof":"hello proof2","Sign":"hello sign2"},"109":{"DataHash":"DataHash3","Proof":"hello proof3","Sign":"hello sign3"}}}`

Do I need to worry about that?

What is the next step? I saw there is a library file generated `libidchain.dylib`. I guess it is the DID library that I am supposed to use on the mac app? Maybe iOS app as well?

**Comment by heropan** [comment]
This repo we are working on it to support android platform. So, It will not be stable. You don’t need to worry about the errors you saw. You can take a look at [Elastos.Org.Mobile] that depends on this repo about next step.

**Comment by heropan** [comment]
@voyage11 We're working on this repo to support Android platform (IOS later).  It's not stable currently. You don’t need to worry about the error messages you saw. You can take a look at [Elastos.ORG.Wallet.Mobile](git@github.com:elastos/Elastos.ORG.Wallet.Mobile.git) which depends on this repo about next step.

By the way, since this is not a build issue, I closed it.

**Comment by voyage11** [comment]
@heropan Ok. If it is not a build issue, it is the documentation issue then. 

Are you able to update the documentation mention that this repo only support Android for now and iOS and other platforms will be supported in near future? If not, another developer like me could potentially waste a few hours of his/her time trying to figure out how to use this repo.
